---
# yum variables can be checked using this command:
#   $ python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'

epel_repoinstaller_url: "{{ vagrant_repo_base_dir }}epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_gpgkey_url:        "{{ vagrant_repo_base_dir }}RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repo:
  EPEL:
    file: epel
    enabled: "{{ epel_enabled }}"
    baseurl: "{{ vagrant_repo_base_dir }}epel/"
