---
# yum variables can be checked using this command:
#   $ python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'

epel_repoinstaller_url:     "http://download.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_gpgkey_url:            "http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repo:
  EPEL:
    file: epel
    enabled: "{{ epel_enabled }}"
    mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch"
